"""Generate the README tables from sources.json."""

from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "sources.json"
README = ROOT / "README.md"


def md(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", "<br>")


def links(raw: str) -> str:
    urls = [part.strip() for part in raw.splitlines() if part.strip()]
    return " ".join(f"[{index}]({url})" for index, url in enumerate(urls, start=1))


def anchor(value: str) -> str:
    """Match GitHub's practical heading slug for our category labels."""
    value = value.lower().replace(" ", "-")
    value = re.sub(r"[^\w\-\u4e00-\u9fff]", "", value)
    return re.sub(r"-+", "-", value).strip("-")


def main() -> None:
    document = json.loads(DATA.read_text(encoding="utf-8"))
    entries = document["entries"]
    grouped: dict[str, list[dict[str, object]]] = defaultdict(list)
    for entry in entries:
        grouped[str(entry["来源类别"])].append(entry)

    level_counts = Counter(str(entry["证据等级"]) for entry in entries)
    category_counts = Counter(str(entry["来源类别"]) for entry in entries)
    lines = [
        "# Awesome 2API",
        "",
        "> A source-backed index of web, app, desktop, browser, and coding assistants that have been wrapped into generic chat APIs.",
        "> 将网页、App、桌面端、浏览器和编码助手反代为通用聊天接口的证据型目录。",
        "",
        "[![Awesome](https://awesome.re/badge.svg)](https://awesome.re)",
        "",
        "This list records the reference implementation and its evidence. It is an index, not a claim that every entry still works, is permitted in every region, or provides free capacity. Check the linked project, terms, and account requirements before use.",
        "",
        "本库只收录已经出现公开反代、适配器或 Provider 证据的来源。它不是可用性、额度或许可的保证；请在使用前核对上游项目、服务条款、地区限制和账号要求。",
        "",
        "## Scope",
        "",
        "Included:",
        "- A public implementation or provider declaration that produces a generic chat interface.",
        "- Web sessions, embedded app assistants, browser assistants, coding subscriptions, and similar LLM chat sources.",
        "- OpenAI-compatible Chat Completions, OpenAI Responses, Anthropic Messages, or a clearly equivalent HTTP/SSE contract.",
        "",
        "Excluded:",
        "- Official API-only SDKs and ordinary model catalogs.",
        "- Media-only tools, business transaction APIs, or App capability APIs without a generic chat output.",
        "- Product candidates or reverse-engineering notes without a public adapter/provider reference.",
        "",
        "## Evidence levels",
        "",
        "| Level | Meaning | Count |",
        "| --- | --- | ---: |",
        f"| A-直接反代 | A public project directly converts the source into a generic API. | {level_counts.get('A-直接反代', 0)} |",
        f"| B-聚合适配 | A maintained aggregator or provider catalog exposes an adapter reference; details still need review. | {level_counts.get('B-聚合适配', 0)} |",
        f"| C-包装层 | A generic wrapper exists through a CLI, language server, or app-server boundary. | {level_counts.get('C-包装层', 0)} |",
        "",
        "The labels describe evidence, not quality, legality, uptime, or available quota.",
        "",
        "## Catalog",
        "",
        f"The current snapshot contains **{len(entries)} source families** across **{len(grouped)} categories**. The machine-readable source is [`sources.json`](sources.json), and this table is generated by [`scripts/generate_readme.py`](scripts/generate_readme.py).",
        "",
        "| Category | Entries |",
        "| --- | ---: |",
    ]
    for category in sorted(category_counts):
        lines.append(f"| [{category}](#{anchor(category)}) | {category_counts[category]} |")
    lines.append("")

    for category in sorted(grouped):
        lines.extend(
            [
                f"### {category}",
                "",
                "| Source | Generic interface | Evidence | Reference project | Shape | Status |",
                "| --- | --- | --- | --- | --- | --- |",
            ]
        )
        for entry in sorted(grouped[category], key=lambda item: int(item["序号"])):
            lines.append(
                "| "
                + " | ".join(
                    [
                        md(entry["来源家族"]),
                        md(entry["通用接口"]),
                        md(entry["证据等级"]),
                        md(entry["参考项目"]) + " (" + links(str(entry["参考URL"])) + ")",
                        md(entry["接入形态"]),
                        md(entry["状态"]),
                    ]
                )
                + " |"
            )
        lines.append("")

    lines.extend(
        [
            "## Data and maintenance",
            "",
            "Each row keeps the source family, category, generic output protocol, evidence level, reference project, public URL, connection shape, conclusion, status, and inventory number. See [`CONTRIBUTING.md`](CONTRIBUTING.md) for the admission rules.",
            "",
            "```text",
            "python scripts/validate.py",
            "python scripts/generate_readme.py",
            "```",
            "",
            "Do not submit cookies, tokens, personal data, private endpoints, or instructions for bypassing authentication, quotas, paywalls, or access controls. See [`SECURITY.md`](SECURITY.md).",
            "",
            "## Contributing",
            "",
            "See [`CONTRIBUTING.md`](CONTRIBUTING.md) for the evidence and review rules.",
            "",
            "## Related implementation",
            "",
            "[Clash of Tokens](https://github.com/dajiaohuang/clash_of_tokens) is a separate native Go gateway project. This repository is the public index; it does not bundle upstream credentials or claim that every catalog entry is implemented there.",
            "",
            "## License",
            "",
            "MIT. See [`LICENSE`](LICENSE).",
            "",
        ]
    )
    README.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
